version: '3'
services:
  web:
    image: "registry.facha.dev/facha/intelhub:latest"
    volumes:
      - ./service-config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./service-config/nginx/sites:/etc/nginx/conf.d:ro
      - ./.env:/var/www/intelhub/.env:ro
      - ./:/var/www/intelhub
    ports:
      - "80:80"
    depends_on:
      - postgresql
      - rabbitmq
      - memcached
  worker:
    image: "registry.facha.dev/facha/intelhub:latest"
    volumes:
      - ./service-config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./service-config/nginx/sites:/etc/nginx/conf.d:ro
      - ./.env:/var/www/intelhub/.env:ro
      - ./service-config/supervisor/supervisord-worker.conf:/etc/supervisor/conf.d/supervisord.conf:ro
      - ./:/var/www/intelhub
    ports:
      - "5000-5100:5000-5100"
    depends_on:
      - postgresql
      - rabbitmq
      - memcached
  postgresql:
    image: postgis/postgis:14-3.3-alpine
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    ports:
      - "5432:5432"
    env_file:
      - service-config/pg/pg.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./service-config/pg/postgres.conf:/etc/postgresql/postgresql.conf:ro

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - service-config/pgadmin/pgadmin.env
    ports:
      - "7474:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgresql
  rabbitmq:
    image: rabbitmq:3.11-management
    ports:
      #      - '5672:5672' # No remote access is needed
      - '15672:15672'
  memcached:
    image: memcached
    ports:
      - 11211:11211
volumes:
  postgres-data:
  pgadmin-data:

