version: '3'
services:
  web:
    image: "registry.facha.dev/facha/intelhub:latest"
    volumes:
      - ./service-config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./service-config/nginx/sites:/etc/nginx/conf.d:ro
      - ./.env:/var/www/intelhub/.env:ro
    ports:
      - "80:80"
  worker:
    image: "registry.facha.dev/facha/intelhub:latest"
    volumes:
      - ./service-config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./service-config/nginx/sites:/etc/nginx/conf.d:ro
      - ./.env:/var/www/intelhub/.env:ro
      - ./service-config/supervisor/supervisord-worker.conf:/etc/supervisor/conf.d/supervisord.conf:ro
    ports:
      - "5000-5100:5000-5100"
  postgresql:
    image: postgis/postgis:14-3.3-alpine
    ports:
      - "5432:5432"
    env_file:
      - service-config/pg/pg.env
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - service-config/pgadmin/pgadmin.env
    ports:
      - "7474:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgresql
volumes:
  postgres-data:
  pgadmin-data:

