version: '3'
services:
  web:
    image: "registry.facha.dev/facha/intelhub:latest"
    volumes:
      - ./:/var/www/intelhub
      - ./service-config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./service-config/nginx/sites:/etc/nginx/conf.d:ro
    ports:
      - "80:80"
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: intelhub
      MYSQL_USER: intelhub
      MYSQL_PASSWORD: intelhub
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
volumes:
  mysql:
    driver: local
