version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/intelhub
      - ./service-config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./service-config/nginx/sites:/etc/nginx/conf.d:ro
    ports:
      - "80:80"
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/intelhub
      - ./service-config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./service-config/nginx/sites:/etc/nginx/conf.d:ro
      - ./service-config/supervisor/supervisord-worker.conf:/etc/supervisor/conf.d/supervisord.conf:ro
    ports:
      - "5000-5100:5000-5100"
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: intelhub
      MYSQL_USER: intelhub
      MYSQL_PASSWORD: intelhub
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
  pma:
    image: "phpmyadmin/phpmyadmin"
    depends_on:
      - mysql
    environment:
      - PMA_HOSTS=mysql
    ports:
      - 7474:80
volumes:
  mysql:
    driver: local
